Global variables replacement
jakejh/metapredict pull request #23
Opened 2021-08-09 19:28 UTC by JSchoenbachler

Replacing global variables. Also ran into an issue with vignettes failing because of vroom but fixed that too!

2021-08-09 21:49 UTC, jakejh requested changes

2021-08-09 21:49 UTC, jakejh commented on R/metapredict_process.R
> +#' @importMethodsFrom rlang .data
.data is not a method, this should just be `importFrom`, same as before.

2021-08-09 21:49 UTC, jakejh commented on DESCRIPTION
> +Version: 1.1.1
devtools::check says Depends should be 3.5 instead of 3.2, based on serialized objects. Do you see this as well?

2021-08-10 14:20 UTC, JSchoenbachler reviewed
Fixed requested changes

2021-08-10 14:59 UTC, jakejh approved these changes

2021-08-11 14:47 UTC, merged